site_name: Single Source Tutorial 

# Repository
repo_url: https://github.com/freesig/single_source 

nav:
  - What to use single source for: usecase.md
  - Creating an integration test - tutorial: tutorial.md
  - Rendered version: tutorial_rendered.md
  - Runnable - tutorial: runnable_tutorial.md
  - Rendered version: runnable_tutorial_rendered.md

# Theme
theme:
  name: 'material'
  feature:
    tabs: true
  font:
    text: 'Work Sans'
    code: 'Roboto Mono'
  palette:
    primary: 'indigo'
    accent: 'indigo'

# Extensions
markdown_extensions:
  - admonition
  - meta
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.tilde
  - pymdownx.emoji
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.extra
  - pymdownx.betterem
